# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_slidemenu_dividend_tracker.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(376, 505)
        Form.setStyleSheet("#frame_header,\n"
"#frame_header_2,\n"
"#frame_header_3 {\n"
"background-color: #E9EDF1;\n"
"border-radius: 8px;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_body_left_frame = QtWidgets.QFrame(Form)
        self.main_body_left_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_body_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_left_frame.setObjectName("main_body_left_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_body_left_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.main_body_left_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_header = QtWidgets.QFrame(self.frame)
        self.frame_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_header)
        self.horizontalLayout_2.setContentsMargins(6, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_header)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_header)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.main_body_left_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.button_new_portfolio = QtWidgets.QPushButton(self.frame_3)
        self.button_new_portfolio.setObjectName("button_new_portfolio")
        self.verticalLayout_5.addWidget(self.button_new_portfolio)
        self.button_new_share = QtWidgets.QPushButton(self.frame_3)
        self.button_new_share.setObjectName("button_new_share")
        self.verticalLayout_5.addWidget(self.button_new_share)
        self.button_new_booking = QtWidgets.QPushButton(self.frame_3)
        self.button_new_booking.setObjectName("button_new_booking")
        self.verticalLayout_5.addWidget(self.button_new_booking)
        self.button_table_settings = QtWidgets.QPushButton(self.frame_3)
        self.button_table_settings.setObjectName("button_table_settings")
        self.verticalLayout_5.addWidget(self.button_table_settings)
        self.verticalLayout.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.main_body_left_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PORTFOLIO"))
        self.button_new_portfolio.setText(_translate("Form", "New portfolio..."))
        self.button_new_portfolio.setProperty("class", _translate("Form", "btn_slidemenu"))
        self.button_new_share.setText(_translate("Form", "New share..."))
        self.button_new_share.setProperty("class", _translate("Form", "btn_slidemenu"))
        self.button_new_booking.setText(_translate("Form", "New booking..."))
        self.button_new_booking.setProperty("class", _translate("Form", "btn_slidemenu"))
        self.button_table_settings.setText(_translate("Form", "Table settings..."))
        self.button_table_settings.setProperty("class", _translate("Form", "btn_slidemenu"))
