# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'savings_plan_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(875, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(".btn_mainwindow {\n"
"border-radius: 8px;\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"}\n"
".btn_mainwindow:hover {\n"
"border-color: rgb(136, 138, 133);\n"
"border-radius: 8px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"}\n"
".btn_slidemenu {\n"
"background-color: #828282;\n"
"padding-left: 2px;\n"
"padding-right: 2px;\n"
"padding-top: 2px;\n"
"padding-bottom: 2px;\n"
"}\n"
".btn_mainbody {\n"
"background-color: #828282;\n"
"padding-left: 4px;\n"
"padding-right: 4px;\n"
"padding-top: 2px;\n"
"padding-bottom: 2px;\n"
"}\n"
"#MainWindow {\n"
" background-color: #E9EDF1; \n"
"}\n"
"#frame_body_workareas,\n"
"#frame_header,\n"
"#frame_body,\n"
"#frame_footer {\n"
"background-color: #E9EDF1;\n"
"}\n"
"#frame_body_slidemenu_core,\n"
"#frame_body_mainbody {\n"
"border-radius: 8px;\n"
"background-color: #BFCBD9;\n"
"}\n"
"#mainbody_workarea_01,\n"
"#mainbody_workarea_02,\n"
"#slidemenu_workarea_01,\n"
"#slidemenu_workarea_02 {\n"
"background-color: #BFCBD9;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_header = QtWidgets.QFrame(self.centralwidget)
        self.frame_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_header)
        self.horizontalLayout.setContentsMargins(8, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_header_left = QtWidgets.QFrame(self.frame_header)
        self.frame_header_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_header_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header_left.setObjectName("frame_header_left")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_header_left)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_slidemenu = QtWidgets.QPushButton(self.frame_header_left)
        self.btn_slidemenu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/menu-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_slidemenu.setIcon(icon)
        self.btn_slidemenu.setIconSize(QtCore.QSize(25, 25))
        self.btn_slidemenu.setFlat(True)
        self.btn_slidemenu.setObjectName("btn_slidemenu")
        self.horizontalLayout_7.addWidget(self.btn_slidemenu)
        self.btn_new = QtWidgets.QPushButton(self.frame_header_left)
        self.btn_new.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/note-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new.setIcon(icon1)
        self.btn_new.setIconSize(QtCore.QSize(25, 25))
        self.btn_new.setFlat(True)
        self.btn_new.setObjectName("btn_new")
        self.horizontalLayout_7.addWidget(self.btn_new)
        self.btn_open = QtWidgets.QPushButton(self.frame_header_left)
        self.btn_open.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/folder-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open.setIcon(icon2)
        self.btn_open.setIconSize(QtCore.QSize(25, 25))
        self.btn_open.setFlat(True)
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_7.addWidget(self.btn_open)
        self.btn_save_as = QtWidgets.QPushButton(self.frame_header_left)
        self.btn_save_as.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/content-save-edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save_as.setIcon(icon3)
        self.btn_save_as.setIconSize(QtCore.QSize(25, 25))
        self.btn_save_as.setFlat(True)
        self.btn_save_as.setObjectName("btn_save_as")
        self.horizontalLayout_7.addWidget(self.btn_save_as)
        self.horizontalLayout.addWidget(self.frame_header_left, 0, QtCore.Qt.AlignLeft)
        self.frame_header_center = QtWidgets.QFrame(self.frame_header)
        self.frame_header_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_header_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header_center.setObjectName("frame_header_center")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_header_center)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_app_icon = QtWidgets.QLabel(self.frame_header_center)
        self.lbl_app_icon.setMinimumSize(QtCore.QSize(30, 30))
        self.lbl_app_icon.setMaximumSize(QtCore.QSize(30, 30))
        self.lbl_app_icon.setText("")
        self.lbl_app_icon.setPixmap(QtGui.QPixmap(":/icons/icons/chart-bar.svg"))
        self.lbl_app_icon.setScaledContents(True)
        self.lbl_app_icon.setObjectName("lbl_app_icon")
        self.horizontalLayout_6.addWidget(self.lbl_app_icon, 0, QtCore.Qt.AlignRight)
        self.lbl_app_name = QtWidgets.QLabel(self.frame_header_center)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_app_name.setFont(font)
        self.lbl_app_name.setObjectName("lbl_app_name")
        self.horizontalLayout_6.addWidget(self.lbl_app_name)
        self.horizontalLayout.addWidget(self.frame_header_center)
        self.frame_header_right = QtWidgets.QFrame(self.frame_header)
        self.frame_header_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_header_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header_right.setObjectName("frame_header_right")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_header_right)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_info = QtWidgets.QPushButton(self.frame_header_right)
        self.btn_info.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/information-outline.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_info.setIcon(icon4)
        self.btn_info.setIconSize(QtCore.QSize(25, 25))
        self.btn_info.setFlat(True)
        self.btn_info.setObjectName("btn_info")
        self.horizontalLayout_8.addWidget(self.btn_info)
        self.horizontalLayout.addWidget(self.frame_header_right, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_header, 0, QtCore.Qt.AlignTop)
        self.frame_body = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_body.sizePolicy().hasHeightForWidth())
        self.frame_body.setSizePolicy(sizePolicy)
        self.frame_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body.setObjectName("frame_body")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_body)
        self.horizontalLayout_3.setContentsMargins(0, 0, 12, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_body_workareas = QtWidgets.QFrame(self.frame_body)
        self.frame_body_workareas.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_body_workareas.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_body_workareas.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_body_workareas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body_workareas.setObjectName("frame_body_workareas")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_body_workareas)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_workareas_buttons = QtWidgets.QFrame(self.frame_body_workareas)
        self.frame_workareas_buttons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_workareas_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_workareas_buttons.setObjectName("frame_workareas_buttons")
        self.verticalLayoutWorkareaButtons = QtWidgets.QVBoxLayout(self.frame_workareas_buttons)
        self.verticalLayoutWorkareaButtons.setContentsMargins(0, 3, 0, 0)
        self.verticalLayoutWorkareaButtons.setSpacing(3)
        self.verticalLayoutWorkareaButtons.setObjectName("verticalLayoutWorkareaButtons")
        self.verticalLayout_2.addWidget(self.frame_workareas_buttons, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_3.addWidget(self.frame_body_workareas)
        self.frame_body_slidemenu = QtWidgets.QFrame(self.frame_body)
        self.frame_body_slidemenu.setMaximumSize(QtCore.QSize(390, 16777215))
        self.frame_body_slidemenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_body_slidemenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body_slidemenu.setObjectName("frame_body_slidemenu")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_body_slidemenu)
        self.horizontalLayout_11.setContentsMargins(0, 0, 12, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_body_slidemenu_core = QtWidgets.QFrame(self.frame_body_slidemenu)
        self.frame_body_slidemenu_core.setMaximumSize(QtCore.QSize(390, 16777215))
        self.frame_body_slidemenu_core.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_body_slidemenu_core.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body_slidemenu_core.setObjectName("frame_body_slidemenu_core")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_body_slidemenu_core)
        self.horizontalLayout_9.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.stackedWidget_slidemenu = QtWidgets.QStackedWidget(self.frame_body_slidemenu_core)
        self.stackedWidget_slidemenu.setObjectName("stackedWidget_slidemenu")
        self.horizontalLayout_9.addWidget(self.stackedWidget_slidemenu)
        self.horizontalLayout_11.addWidget(self.frame_body_slidemenu_core, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addWidget(self.frame_body_slidemenu)
        self.frame_body_mainbody = QtWidgets.QFrame(self.frame_body)
        self.frame_body_mainbody.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_body_mainbody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body_mainbody.setObjectName("frame_body_mainbody")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_body_mainbody)
        self.horizontalLayout_10.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.stackedWidget_mainbody = QtWidgets.QStackedWidget(self.frame_body_mainbody)
        self.stackedWidget_mainbody.setObjectName("stackedWidget_mainbody")
        self.horizontalLayout_10.addWidget(self.stackedWidget_mainbody)
        self.horizontalLayout_3.addWidget(self.frame_body_mainbody)
        self.verticalLayout.addWidget(self.frame_body)
        self.frame_footer = QtWidgets.QFrame(self.centralwidget)
        self.frame_footer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_footer.setObjectName("frame_footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_footer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_footer_left = QtWidgets.QFrame(self.frame_footer)
        self.frame_footer_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_footer_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_footer_left.setObjectName("frame_footer_left")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_footer_left)
        self.horizontalLayout_5.setContentsMargins(3, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_version = QtWidgets.QLabel(self.frame_footer_left)
        self.lbl_version.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_version.setObjectName("lbl_version")
        self.horizontalLayout_5.addWidget(self.lbl_version, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addWidget(self.frame_footer_left)
        self.frame_footer_center = QtWidgets.QFrame(self.frame_footer)
        self.frame_footer_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_footer_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_footer_center.setObjectName("frame_footer_center")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_footer_center)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_centericon = QtWidgets.QLabel(self.frame_footer_center)
        self.lbl_centericon.setText("")
        self.lbl_centericon.setPixmap(QtGui.QPixmap(":/icons/icons/finance.svg"))
        self.lbl_centericon.setScaledContents(True)
        self.lbl_centericon.setObjectName("lbl_centericon")
        self.horizontalLayout_4.addWidget(self.lbl_centericon, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_footer_center, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.frame_footer_right = QtWidgets.QFrame(self.frame_footer)
        self.frame_footer_right.setMinimumSize(QtCore.QSize(20, 20))
        self.frame_footer_right.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_footer_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_footer_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_footer_right.setObjectName("frame_footer_right")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_footer_right)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_sizegrip = QtWidgets.QLabel(self.frame_footer_right)
        self.lbl_sizegrip.setText("")
        self.lbl_sizegrip.setPixmap(QtGui.QPixmap(":/icons/icons/resize-bottom-right.svg"))
        self.lbl_sizegrip.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lbl_sizegrip.setObjectName("lbl_sizegrip")
        self.gridLayout.addWidget(self.lbl_sizegrip, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_footer_right, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.frame_footer, 0, QtCore.Qt.AlignBottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_slidemenu.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_slidemenu.setProperty("class", _translate("MainWindow", "btn_mainwindow"))
        self.btn_new.setProperty("class", _translate("MainWindow", "btn_mainwindow"))
        self.btn_open.setProperty("class", _translate("MainWindow", "btn_mainwindow"))
        self.btn_save_as.setProperty("class", _translate("MainWindow", "btn_mainwindow"))
        self.lbl_app_name.setText(_translate("MainWindow", "SAVINGS PLAN"))
        self.btn_info.setProperty("class", _translate("MainWindow", "btn_mainwindow"))
        self.lbl_version.setText(_translate("MainWindow", "Version 0.1"))
from src import icons_rc
